config/routes.rb
Rails.application.routes.draw do

  root 'zadankai#home'
  get 'zadankai/about'
  get 'zadankai/term'
  get 'zadankai/privacy'

  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # facebook oath
  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        username: auth.info.name,
        email: auth.info.email,
        remote_avatar: auth.info.image,
        password: Devise.friendly_token[0, 20]
      )
    end

    user
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    callback_from :facebook
  end
  
  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
  before_action :set_user, only:[:show, :edit, :update, :joiner]
  before_action :matched_user, only:[:edit, :update]

  def index
    @users = User.all
  end

  def show
    @userName = @user.username
    # 自分のプロジェクト一覧
   
    # 参加中のプロジェクト一覧
    
  end

  def edit
    @prifectures = ["選択してください","北海道", "青森県", "岩手県", "宮城県", "秋田県", "山形県", "福島県", "茨城県", "栃木県", "群馬県", "埼玉県", "千葉県", "東京都", "神奈川県", "新潟県", "富山県", "石川県", "福井県", "山梨県", "長野県", "岐阜県", "静岡県", "愛知県", "三重県", "滋賀県", "京都府", "大阪府", "兵庫県", "奈良県", "和歌山県", "鳥取県", "島根県", "岡山県", "広島県", "山口県", "徳島県", "香川県", "愛媛県", "高知県", "福岡県", "佐賀県", "長崎県", "熊本県", "大分県", "宮崎県", "鹿児島県", "沖縄県"]

    @genders = ["選択してください","男","女"]

  end

  def update
    if @user.update(edit_user_params)
      flash[:success] = "プロフィールjは更新されました"
      redirect_to @user
    else
      render 'edit'
    end
  end


  private

  def edit_user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :avatar, :remote_avatar, :place, :birth, :gender, :introduce)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def matched_user

    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% content_for :head do %>
  <meta name="title" content="<%=@user.username %>ページの編集">
  <meta name="description" content="<%=@user.username %>の情報の編集">
<% end %>

<div class="container">
  <div class="row form">
    <div class="col-xs-4 col-xs-offset-4 edit_profile">
      <h2 style="text-align: center;">プロフィール編集</h2>

      <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="field">
          <%= f.label :username, "お名前" %> <em>(最大6文字)</em><br>
          <%= f.text_field :username, autofocus: true, class: 'input form-control' %>
        </div><br/>

        <div class="field">
          <%= f.label :avatar, "プロフィール画像" %>
          <%= f.file_field :avatar, class: "form-control" %>
        </div><br/>

        <div class="field">
          <%= f.label :email, "メールアドレス" %><br />
          <%= f.email_field :email, autofocus: true, class: 'input form-control' %>
        </div><br/>

        <div class="field">
          <%= f.label :place, "現在地" %>
          <%= f.select :place, @prifectures, class: "form-control" %>
        </div><br/>

        <div class="field">
          <%= f.label :gender, "性別" %>
          <%= f.select :gender, @genders, class: "form-control" %>
        </div><br/>

        <div class="birth_date_field">
          <%= f.label :birth, "生年月日" %><br/>
           <%= raw sprintf(
              f.date_select(
                  :birth,
                  use_month_numbers: true,
                  start_year:        1930,
                  end_year:          (Time.now.year - 18),
                  default:           Date.new(1989, 1, 1),
                  date_separator:    '%s'),
              '年 ', '月 ') + '日' %>
        </div><br/>

        <div class="field">
          <%= f.label :パスワード %>
          <% if @validatable %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %><br />
          <%= f.password_field :password, autocomplete: "off", class: 'input form-control' %>
        </div>

        <div class="field">
          <%= f.label :password_confirmation, "パスワード確認" %><br />
          <%= f.password_field :password_confirmation, autocomplete: "off", class: 'input form-control' %>
        </div><br/>

        <div class="actions">
          <%= f.submit "プロフィールを更新する", class: 'btn btn-primary withripple' %>
        </div>
      <% end %><br/>
      <div>

      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% content_for :head do %>
  <meta name="title" content="<%=@user.username %>">
  <meta name="description" content="<%=@user.username %>のマイページ">
<% end %>

<div class="container">
    <div class="row">
        <div class="col-md-3 user-profile">
            <h4><%= @user.username %></h4>
            <% if @user.remote_avatar != nil %>
                <p><%= link_to image_tag(@user.remote_avatar , alt: @user.username), user_path(@user) %></p>
            <% else %>
                <p><%= link_to image_tag(@user.avatar.url , alt: @user.username), user_path(@user) %></p>
            <% end %>
            <p>生年月日: <%= @user.birth %></p>
            <p>性別: <%= @user.gender %></p>
            <p>現在地: <%= @user.place %></p>
            <% if @user == current_user %>
                <%= link_to "プロフィールの編集", edit_user_path(@user), class: "btn btn-large btn-info" %>
            <% end %>

        </div> 
    </div>
</div>