config/routes.rb
Rails.application.routes.draw do

  root 'zadankai#home'
  get 'zadankai/about'
  get 'zadankai/term'
  get 'zadankai/privacy'

  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  resources :users

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <ul class="copyright">
    <li><%= link_to "Zadankaiとは？", zadankai_about_path, class: "link"  %> | <%= link_to "利用規約", zadankai_term_path, class: "link"  %> | <%= link_to "プライバシーポリシー", zadankai_privacy_path, class: "link"  %></li><br/>
    <li>© <%= Date.today.year %> Zadanstyle.com All right reserved.</li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
    <div class="container">
        <%= link_to "Zadankai", root_path, class: "navbar-brand", id: "brand-logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Zadankaiとは？", zadankai_about_path  %></li>
                 <% if user_signed_in? %>
                    <li>
                      <%= link_to "マイページ", user_path(current_user) %>
                    </li>
                    <li>
                      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                    </li>
                <% else %>
                    <li>
                      <%= link_to "ログイン", new_user_session_path, :class => 'post' %>
                    </li>
                    <li>
                      <%= link_to "新規登録", new_user_registration_path, :class => 'post' %>
                    </li>
                <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-left">
                <li>
                    <%= link_to "プロジェクトをはじめる", "#" %>
                </li>
                <li><%= link_to "プロジェクトを探す", '#' %></li>
            </ul>
        </nav>
    </div>

</header>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zadanstyle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: "layouts/header" %>

<%= render 'layouts/messages' %>


  <%= yield %>
<%= render partial: "layouts/footer" %>
</body>
</html>